name: SAST

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  semgrep:
    uses: gridwatch/tooling/.github/workflows/semgrep.yml@main
    secrets:
      SEMGREP_APP_TOKEN: $${{ secrets.SEMGREP_APP_TOKEN }}
